@extends('layouts.app')


@section('content')
<div class="container">
  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 container-contentbar">
    <div class="page-wrap">
      <div class="row row-fluid">
        <div class="col-sm-12">
          <h2><b>Terms of Use</b></h2>
          <hr>
          <div class="entry-content">
          <p>Welcome and thank you for visiting <a href="http://www.suuty.com">www.suuty.com</a> (the “Website”), which is owned and operated by Suuty Technologies (“Suuty”). These Terms of Use (the “Agreement”) constitute a legal agreement between you and Suuty. Please read these Terms of Use (the “Agreement”) carefully before using the Website.</p>
          <p><strong>Acceptance of the Agreement</strong></p>
          <p>Whenever you use the Website or the data and service provided to you by email, you agree to be bound by the Agreement. Should you not want to accept the Agreement, please refrain from use of the Website, email subscription, or make use of services offered by Suuty. Suuty reserves the right to amend the Your use of the website and any services by Suuty, after an amendment has been posted, shall be deemed your acceptance of the revised Terms of Use.</p>
          <p>Suuty reserves the right to cancel the Terms of Use and/or your right to browse and use any or all of the Website or services, without notice, at its complete discretion.</p>
          <p><strong>Nature of Website</strong></p>
          <p>The Website provides real estate related information to consumers and delivers services offered by Suuty. The information provided on the Website is from sources we consider reliable; however, we cannot guarantee their accuracy or completeness as the information is supplied by third parties. This data has not been, and cannot be fully verified by us. You should use your own judgment regarding the merits of any data, individual, or entity that you find on or through the Site.</p>
          <p>The Website may provide information regarding selling or buying a property and such information is provided for educational purposes only. They shall not be construed as legal advice, opinion or recommendation.</p>
          <p><strong>Proprietary Nature of Website and Content</strong></p>
          <p>The Website, and all information, text, images, video, audio and other material posted on or through the Website are protected by copyright, trade-mark, and other intellectual property and proprietary rights laws. All content posted on or through the site, remains the intellectual property of its owner(s), only available for your personal, non-commercial, lawful use.</p>
          <p>You shall not: (i) copy, reproduce, modify, adapt, translate, download, distribute or transmit all or any part of the Content; (ii) perform “data scraping”, “database scraping” or any other activity intended to collect, store, reorganize or manipulate data from the Website or any part of the Content in any form and by any means; (iii) sell, lease, license or otherwise use the Content for commercial, public or non-personal purposes; (iv) modify, remove or cover any trade-mark or proprietary notice included in the Content; (v) decompile, disassemble, decrypt, extract or reverse engineer the Website and its components, including, in particular, the Content, or help anyone do so; or (vi) use the Website in any way that could damage, impair, overburden, disable, or otherwise affect the Website or any services, accounts, servers, networks, resources, linked or accessible through the Website.</p>
          <p><strong>Website Submissions</strong></p>
          <p>You can post and submit messages, data, text, photographs, images, videos and other material (“Your Content”) and interact with Suuty, its employees, mandataries and other users.</p>
          <p>You are fully responsible for the quality and accuracy of Your Content. You agree that Your Content must not violate or infringe upon the rights of others, including intellectual property rights, contravene any law, regulation or government order, or constitute false, misleading, or otherwise illegal information. You agree not to use the Website to harass or abuse, send spam or any unwanted communications, including for commercial purposes, or send unlawful, libelous, obscene, offensive, threatening, aggressive, abusive, discriminatory or otherwise objectionable messages.</p>
          <p>Whenever you post Your Content on the Website or submit Your Content to Suuty, you grant Suuty Technologies an unlimited, irrevocable, non-exclusive, perpetual and royalty-free worldwide licence to: (i) use, copy, store, adapt, translate, modify, create derivative works, transmit, distribute and publicly perform Your Content or make it publicly available for any purpose; and (ii) grant sub-licences to third parties for unlimited rights to exercise any of the foregoing rights. Other than granting the aforementioned licence, you hereby (i) agree to waive all of the moral rights to Your Content in favour of Suuty; (ii) consent to the appearance of your name, address and e-mail address for Your Content, if any, and to the disclosure and/or posting of such information; (iii) acknowledge and agree that Suuty shall not be liable for any loss, damage to or corruption of Your Content; and (iv) acknowledge and agree that the presentations you upload for posting on the Website or that you submit to Suuty shall not be deemed confidential.</p>
          <p>Suuty reserves the right, without any obligation, to monitor the Website, Your Content or any of the content accessible via the Website, in its sole discretion, and to disclose any information necessary in order to comply with any law, regulation or government request, in the interest of operating the Website properly or protecting itself or its users. Suuty may remove Your Content and/or terminate, limit or suspend your access to the Website for any reason.</p>
          <p><strong>Links to Third-Party Sites </strong></p>
          <p>The Website contains links to third-party sites (the “Third-Party Sites”) which will direct you away from the Website. Suuty provides these links for your convenience. The Third-Party Sites are not under Suuty’s control and the links shall not be construed as approval or an endorsement of their content by Suuty. Suuty shall not be liable for the content of Third-Party Sites, the links they contain or any changes or updates made to them, and Suuty makes no warranty in that respect.</p><div class="mailmunch-forms-in-post-middle" style="display: none !important;"></div>
          <p><strong>Links to Suuty Website </strong></p>
          <p>Suuty encourages links to the Website. However, Suuty reserves the right, in its sole discretion, to refuse a link at any time. You agree to remove any link you may have to the Website at Suuty’s request. The link must allow for a new full-screen browser window, only occupied by the Website’s pages. It is strictly prohibited to frame or display the Content in any way that alters its appearance.</p>
          <p><strong>Privacy</strong></p>
          <p>You acknowledge that your personal information may be used by the Website in accordance with the privacy policy available at:</p>
          <p>&nbsp;</p>
          <p><strong>Disclaimer of Liability</strong></p>
          <p>SUUTY’S WEBSITE, SERVICES AND CONTENT ARE PROVIDED “AS IS” AND “AS AVAILABLE”. YOU BROWSE AND USE THE WEBSITE AND ITS FUNCTIONALITIES AT YOUR OWN RISK. SUUTY AND SUUTY TECHNOLOGIES MAKE NO REPRESENTATION OR WARRANTY REGARDING THE WEBSITE, THE CONTENT OR THE SERVICES. SUUTY AND SUUTY TECHNOLOGIES DOES NOT ASSUME RESPONSIBILITY FOR ANY MISLEADING CONTENT OR INCORRECT LISTING INFORMATION.</p>
          <p>THE INFORMATION CONTAINED ON THIS WEBSITE IS IN PART BASED ON USER PROVIDED INFORMATION. THESE USERS ARE RESPONSIBLE FOR ITS ACCURACY AND SUUTY ASSUMES NO RESPONSIBILITY FOR USER PROVIDED INFORMATION COMPLETENESS OR ACCURACY.</p>
          <br>
          <p>SUUTY IS A WEB PLATFORM, NOT A LICENSED BROKERAGE.&nbsp;SUUTY ASSUMES NO LIABILITY FOR THE FAILURE TO SELL OR COMPLETE THE SALE OF YOUR PROPERTY THROUGH THE WEBSITE. SUUTY ASSUMES NO LIABILITY FOR ANY LEGAL DOCUMENTS YOU SIGN THROUGH THE SITE. IT IS RECOMMENDED THAT YOU SEEK LEGAL ADVICE BEFORE SIGNING ANY LEGALLY BINDING DOCUMENTS.</p>
          <p>SUUTY, SUUTY TECHNOLOGIES, THEIR AFFILIATES, DIRECTORS, EMPLOYEES, MANDATARIES, AND LICENSORS, INCLUDING THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, SHALL UNDER NO CIRCUMSTANCES BE LIABLE FOR DAMAGE OF ANY KIND, INCLUDING INDIRECT, SPECIAL OR FORTUITOUS DAMAGE, ARISING DIRECTLY OR INDIRECTLY FROM THE USE OR PERFORMANCE OF THE WEBSITE, THE SERVICES OR THE CONTENT CONTAINED THEREON OR ON ANY OTHER SITE YOU MAY LINK TO THROUGH THE WEBSITE, EVEN IF THEY WERE OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF SUCH DAMAGE.</p>
          <p>SUUTY, SUUTY TECHNOLOGIES, THEIR AFFILIATES, DIRECTORS, EMPLOYEES, MANDATARIES, AND LICENSORS, INCLUDING THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, DISCLAIM ANY LIABILITY FOR THE ACTS, OMISSIONS OR CONDUCT OF ANY THIRD PARTY USING THE WEBSITE AND ITS FUNCTIONALITIES OR THAT OF ANY ADVERTISER OR SPONSOR ON THE WEBSITE (“THIRD-PARTY USERS”) AND SHALL IN NO EVENT BE LIABLE FOR ANY HARM, LOSS OR DAMAGES (INCLUDING SPECIAL, INDIRECT OR INCIDENTAL DAMAGES) OR COSTS ARISING IN ANY MANNER FROM (i) THE ACTS, OMISSIONS OR CONDUCT OF A THIRD-PARTY USER; OR (ii) THE USE OF OR INABILITY TO USE ANYTHING OR ANY SOFTWARE, CONTENT, GOODS OR SERVICES ON OR OFFERED THROUGH A SITE LINKED TO THE WEBSITE.</p>
          <p><strong>Indemnification </strong></p>
          <p>You agree to indemnify, hold harmless and defend Suuty and/or Suuty Technologies, their affiliates, their directors, employees, mandataries, and licensors, including their respective successors and assigns, from and against all claims, demands, liability, costs or expenses of any nature, including legal fees and disbursements arising directly or indirectly from: (i) your violation of the Terms of Use; (ii) your browsing, use or inability to browse or use the Website and/or the Services or any site to which the Website is or may be linked from time to time; (iii) your use of publications, communications, distributions or downloads of any nature via the Website and/or the Services, or your reliance thereon; and/or (iv) your violation of the applicable legislation or regulations. You agree to cooperate with us in contesting any claims.</p>
          <p><strong>Governing Law</strong></p>
          <p>These Terms of Use, as well as your use of the Website and Services, shall be governed by the laws of the Province of British Columbia and the laws of Canada, regardless of conflict of law principles. If the court of law having jurisdiction, rules that any provision of the agreement is invalid, then that provision will be removed from the Terms and the remaining Terms will continue to be valid. The courts in Vancouver, British Columbia, will have exclusive jurisdiction to hear and decide any disputes relating to these Terms of Use.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection
@section('footer')
@include('includes.footer')
@endsection
